[package]
name = "raven"
version = "0.1.0"
authors = ["Gabriel Dos Ramos Albo <dosramosgabriel@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
ravenlib = { path = "src/core", package = "raven-core" }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.8"